### ISSUE TITLE
安装完之后运行ImportError: No module named flask报错

### ISSUE THREAD

**Issue by Jireh012** [Ccapton/brook-web#11]
相关依赖都已经安装，但是最后的时候报错了
Traceback (most recent call last):
  File "brook-web.py", line 16, in <module>
    from flask import Flask,render_template,send_from_directory
ImportError: No module named flask

**Comment by Ccapton** [comment]
> 相关依赖都已经安装，但是最后的时候报错了
> Traceback (most recent call last):
> File "brook-web.py", line 16, in 
> from flask import Flask,render_template,send_from_directory
> ImportError: No module named flask

请确保在root用户下使用命令行，或 sudo pip install -r requirements.txt 再尝试安装依赖

**Comment by Ccapton** [comment]
> ![image](https://user-images.githubusercontent.com/19604856/48235587-5491c000-e3f9-11e8-9354-9251e90840c5.png)
> 已经是在root用户下执行的

请试试 python3.4 brook-web.py 。 实在不行就用Docker部署吧

**Comment by Ccapton** [comment]
> 可以了 用python3.4 执行会报UnicodeEncodeError: 'ascii' codec can't encode相关的错误
> 设置全局的环境变量 export LANG="en_US.UTF-8"，或者在启动命令前加上 PYTHONIOENCODING=utf-8 ，即：PYTHONIOENCODING=utf-8 python3.4 brook-web.py

你设置了字符编码后，现在问题解决了吗
