### ISSUE TITLE
web界面的底部会出现拖动栏

### ISSUE THREAD

**Issue by sxueck** [Ccapton/brook-web#15]
不知道是不是设置了绝对值，1080p的屏幕，底部会出现拖动栏
浏览器：Chrome

**Comment by Ccapton** [comment]
> 不知道是不是设置了绝对值，1080p的屏幕，底部会出现拖动栏
> 浏览器：Chrome

哈哈，不影响使用就行啦，我看什么时候有空增加新的服务

**Comment by sxueck** [comment]
那密码提交的时候能不能不用GET
