### ISSUE TITLE
小建议：加入端口备注

### ISSUE THREAD

**Issue by owenlsa** [Ccapton/brook-web#3]
你好，个人提一个小建议，加入端口号所对应的备注，方便在列表中查看也方便几个朋友合租的时候区分一下，因为怕水表所以我们端口号都是乱七八糟不连续的

**Comment by Ccapton** [comment]
> 你好，个人提一个小建议，加入端口号所对应的备注，方便在列表中查看也方便几个朋友合租的时候区分一下，因为怕水表所以我们端口号都是乱七八糟不连续的

###　提议不错，我尝试优化一下，在创建端口时多加一个备注可选输入框

**Comment by ownelsa** [comment]
> > 你好，个人提一个小建议，加入端口号所对应的备注，方便在列表中查看也方便几个朋友合租的时候区分一下，因为怕水表所以我们端口号都是乱七八糟不连续的
> 
> ###　提议不错，我尝试优化一下，在创建端口时多加一个备注可选输入框

万分感谢！

**Comment by Ccapton** [comment]
> > > 你好，个人提一个小建议，加入端口号所对应的备注，方便在列表中查看也方便几个朋友合租的时候区分一下，因为怕水表所以我们端口号都是乱七八糟不连续的
> > 
> > 
> > ###　提议不错，我尝试优化一下，在创建端口时多加一个备注可选输入框
> 
> 万分感谢！

已经更新了！！
